version: '3'

services:
  mysql:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=admin
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  
  mongo_seed:
    image: mongo
    links:
      - mongodb
    volumes:
      - ./mongo-seed:/mongo-seed
    command:
      mongoimport --host mongodb --db golangApi --collection user --authenticationDatabase admin --username admin --password admin --drop --file /mongo-seed/init.json --jsonArray
